dbt_example:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dbtcurso
      dataset: "{{ env_var ('DBT_DBNAME',   'dbt_dw') }}"
      threads: 4
      keyfile: /home/matheus/dbtcurso-ebc3cec27666.json
